### ISSUE TITLE
Documentation? How to install?

### ISSUE THREAD

**Issue by echofriend** [sbondCo/Casterr#60]
**Description of the new feature**
What is the expected behavior of the proposed feature?
I want to know how to download a setup.exe to install on my pc?

Thanks

**Comment by IRHM** [comment]
Sorry, Casterr is still under development, which is why we don't have any builds/downloads for it.

Since I'm such a nice guy I have built an exe from the main branch, keep in mind it's still in development stages, so the main parts of the app aren't fully done yet. I'm on Linux right now and i'm not able to test the .exe for you. 50/50 chance it works.

You can download it [here](https://ufile.io/03tpamh4) (too big to upload on this message).

If you want help building the app for development, feel free to respond.
